apiVersion: apps/v1
kind: Deployment
metadata:
  name: turion-app-deployment
  labels:
    app: turion-app
spec:
  replicas: 1
  selector:  
    matchLabels:
      app: turion-app
  template:
    metadata:
      labels:
        app: turion-app
    spec:
      containers:
      - name: turion-app 
        image: REPOSITORY_TAG
        ports: 
        - containerPort: 5000 

---
apiVersion: v1 
kind: Service
metadata: 
  name: turion-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: turion-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 30030     